name: Continuous Integration

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker build . -t javascript-sdk-examples
      - name: Run
        run: >
          docker run javascript-sdk-examples
          -e KEY=${{ secrets.KEY }}
          -e SECRET=${{ secrets.SECRET }}
          -e CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
