name: Continuous Integration

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: >
          docker build . -t javascript-sdk-examples
          --build-arg KEY=${{ secrets.KEY }}
          --build-arg SECRET=${{ secrets.SECRET }}
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
      - name: Run
        run: docker run javascript-sdk-examples
